Change `Object.defineProperty` target object
The current implementation doesn't allow creating more than 1 instance and throws the following error in such case:
``` 
TypeError: Cannot redefine property: name
```

The reason is that `Object.defineProperty` defines properties directly for `Logable.prototype` instead of the instance being processed.